### ISSUE TITLE
Are you accepting PRs?

### ISSUE THREAD

**Issue by MrSurly** [ebuller/openfixture#6]
I'm doing active development on this, in a fork.  Would PRs be accepted?

* Modified locking tabs to be more robust
* Made 2d rendering very fast
* 3d rendering optional (but still faster than it was)
* Adding an option to rotate the PCB before generating the fixture

**Comment by tinylabs** [comment]
​Hi Eric,

Definitely interested in pull requests. It's been more or less unmaintained
while I've been stuck on other projects. I'd like to clean it up and
integrate your changes but I won't have the cycles until January. I'd also
like to integrate it as a plugin to Pcbnew to make it easier for other
people to use it.

Appreciate the help!
-Elliot​

**Comment by MrSurly** [comment]
I'm also swamped.  All my changes are committed to master; I'll break them out logically, with separate PRs for each, when time allows.

I never did get the "rotate PCB" option to work; the `pcbnew.Board` object does indeed have a `Rotate` method, but it segfaults somwhere in WxWindows when used.

**Comment by MrSurly** [comment]
Submitting several PRs today. 

I have a combined version, if desired.

**Comment by tinylabs** [comment]
Thanks Eric, looks good. In China right now for work but once I get back
I'll integrate those in.
